name: Node Continuous Integration
on: [push]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
      echo This demo file shows a 
      echo very basic and easy-to-understand workflow.